language: csharp
mono: none
dotnet: 2.0.0
jobs:
    include:
        - stage: frontendBuild
          script: 
            - cd src/Dashboard.WebApi/developersDashboardFrontEnd
            - npm install
            - npm build
            - npm test
        - stage: backendBuild
          script:
            - dotnet restore ./src
            - dotnet build ./src/Dashboard.sln
