language: csharp
mono: none
dotnet: 2.0.0
sudo: required
notifications:
   slack: innoprojectsummer2018:Me0KNpSZ1ES1OnWrwTUoD2Y7
env:
  - DOCKER_COMPOSE_VERSION=1.20.1
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker ps
stages:
  - build_all
  - unit_tests_backend
  - name: deploy_images_to_registry
    if: branch = develop
  - name: deploy_to_heroku
    if: branch = develop
jobs:
    include:
        - stage: build_all
          script: docker-compose -f ./src/docker-compose.yml build dashboard.webapi
        - script: docker-compose -f ./src/docker-compose.yml build dashboard.web

        - stage: unit_tests_backend
          script:
            - docker-compose -f ./src/docker-compose.webapi.unittests.yml run --rm webapi.unittests

        - stage: deploy_images_to_registry
          script:
            - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
            - docker-compose -f ./src/docker-compose.yml build dashboard.webapi
            - docker-compose -f ./src/docker-compose.yml push dashboard.webapi
        - script:
            - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
            - docker-compose -f ./src/docker-compose.yml build dashboard.web
            - docker-compose -f ./src/docker-compose.yml push dashboard.web

        - stage: deploy_to_heroku
          script:
            - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
            - docker pull registry.hub.docker.com/randomdocker729/cidashboard-webapi:latest
            - docker tag registry.hub.docker.com/randomdocker729/cidashboard-webapi:latest registry.heroku.com/cidasherapi/web
            - docker push registry.heroku.com/cidasherapi/web
        - script:
          - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
          - docker pull registry.hub.docker.com/randomdocker729/cidashboard-frontend:latest
          - docker tag registry.hub.docker.com/randomdocker729/cidashboard-frontend:latest registry.heroku.com/cidasher/web
          - docker push registry.heroku.com/cidasher/web