version: '3.6'

services:
  dashboard.webapi:
    image: dashboardwebapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  dashboard.web:
    image: dashboardfrontend
    environment:
      - API_HOST=cidasherapi.herokuapp.com
    build:
      context: Dashboard.WebApi/developersDashboardFrontEnd
      dockerfile: Dockerfile
    depends_on:
      - dashboard.webapi
