version: '3.6'

services:
  dashboard.webapi:
    image: dashboardwebapi
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"

  dashboard.web:
    image: dashboardfrontend
    environment:
      - PORT=4200
    build:
      context: Dashboard.WebApi/developersDashboardFrontEnd
      dockerfile: Dockerfile.web
    ports:
      - "4200:4200"
    depends_on:
      - dashboard.webapi
