version: '3.6'
services:
  webapi.unittests:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - .:/code
    command:
      - /bin/bash
      - /code/Dashboard.UnitTests/run-tests.sh

  frontend.test:
    build:
      context: ./Dashboard.WebApi/developersDashboardFrontEnd
      dockerfile: Dockerfile.tests
