version: '3.6'

services:
  dashboard.webapi:
    image: dashboardwebapi
    build:
      context: .
      dockerfile: Dashboard.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"

  dashboard.frontend:
    image: dashboardfrontend
    environment:
      NODE_ENV: production
    build:
      context: Dashboard.WebApi/developersDashboardFrontEnd
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "80:80"
    depends_on:
      - dashboard.webapi
